### PR TITLE
Fixing up for LinqPad

### PR DESCRIPTION
**Pull request by rajyraman**
1. Order entity by schema name
2. Ignore private entities
3. Upgrade to .net 4.6.2

### CODE REVIEW

**Comment by magesoe** [comment]
Next time, please split the PR into smaller pieces. I would love to merge 1. and 2. right away. However, I believe you're not upgrading to .net 4.6.2, since this was already done in version 1.5.0 according to the release notes. What is it actually you're adding as dependencies in the .fsproj file?

**Comment by rajyraman** [comment]
Not sure how this happened. I will check again regarding Framework version

**Comment by magesoe** [comment]
Added in 1.7.3

**Comment by TomMalow** [comment]
Hi @rajyraman 

We have released your changes in the latest version but I'm going to revert the filtering of private entities. After testing along with a discussion with the other maintainers we found that this change constricts the tool more than necessary. 

F.ex. I have a project that fails to build now as it uses private entities in XrmMockup test (e.g. routing rules). I can also see that some might use these entities in their plugins. Their are other private entities that might also be used in the same way.

We already filter out entities based on the solution. Which I see as sufficient. Is there a particular reason why you don't want private entities?

**Comment by rajyraman** [comment]
@TomMalow - I don't remember exactly why I removed Private Entities. If it is impacting other functionalities, please roll it back.

**Pull request merged**
