### PR TITLE
Added fix for (virtual/multiselect) optionset without any options.

### PR DESCRIPTION
**Pull request by robertraaijmakers**
This pull request is a fix for #33

### CODE REVIEW

**Comment by magesoe** [comment]
Nice catch, added in 1.8.1

**Comment by robertraaijmakers** [comment]
Hi @magesoe, thank you! Is there a known date when version 1.8.1 will be available?

**Comment by magesoe** [comment]
It is 
image

**Comment by robertraaijmakers** [comment]
Ah, I see, we use another package, is there any difference?

image

**Comment by magesoe** [comment]
It would seem I have made a mistake when pushing the package, will fix right away

**Comment by magesoe** [comment]
Looks like the new project setup simply used the project name as a fallback. I have fixed it and pushed 1.8.1

**Comment by robertraaijmakers** [comment]
Thank you! Updated the package and works like a charm.

**Pull request merged**
